# Generated by Django 5.1.3 on 2024-12-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_friendrequest_receiver_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
