# Generated by Django 5.1.3 on 2024-12-14 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('friends', '0002_alter_friendrequest_receiver_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('profile1', 'profile2')},
        ),
        migrations.AddField(
            model_name='friendship',
            name='profile1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friends1', to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendship',
            name='profile2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friends2', to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user2',
        ),
    ]
