# Generated by Django 5.1.3 on 2024-12-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_alter_friendship_unique_together_friendship_profile1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
